const HELPER = "http://127.0.0.1:43127";
chrome.action.onClicked.addListener(async (tab) => {
  if (!tab.id || !/^https:\/\/(www\.|m\.)?blog\.naver\.com\//i.test(tab.url || "")) return;
  try { const response = await fetch(`${HELPER}/health`); if (!response.ok) throw new Error("HELPER_NOT_READY"); const packet = await fetch(`${HELPER}/packet/latest`).then((value) => value.json()); await chrome.tabs.sendMessage(tab.id, { type: "DEVLOG_PACKET_READY", packet }); } catch (error) { console.warn(error instanceof Error ? error.message : String(error)); }
});
chrome.runtime.onMessage.addListener((message, sender, sendResponse) => {
  if (message?.type !== "DEVLOG_INSPECT_ALL_FRAMES" || !message.tabId) return;
  chrome.scripting.executeScript({ target: { tabId: message.tabId, allFrames: true }, func: () => {
    const visible = (node) => { const box = node.getBoundingClientRect(); return box.width > 0 && box.height > 0; };
    const attrs = (node) => [...node.attributes].filter((item) => item.name.startsWith("data-")).map((item) => item.name).slice(0, 8);
    const ancestors = (node) => { const result = []; let current = node.parentElement; for (let i = 0; i < 5 && current; i += 1, current = current.parentElement) result.push({ className: String(current.className || "").slice(0, 100), role: current.getAttribute("role"), data: attrs(current) }); return result; };
    const count = (selector) => document.querySelectorAll(selector).length;
    const candidates = [...document.querySelectorAll("[contenteditable='true'], textarea, input, [role='textbox'], [aria-multiline='true'], [data-placeholder]")].filter(visible);
    const diagnostics = candidates.slice(0, 30).map((node) => { const box = node.getBoundingClientRect(); const before = getComputedStyle(node, "::before").content; const after = getComputedStyle(node, "::after").content; const meta = `${node.getAttribute("aria-label") || ""} ${node.getAttribute("placeholder") || ""} ${node.getAttribute("data-placeholder") || ""} ${node.className || ""} ${ancestors(node).map((item) => `${item.className} ${item.role || ""}`).join(" ")} ${before} ${after}`; return { tagName: node.tagName, contenteditable: node.getAttribute("contenteditable"), role: node.getAttribute("role"), ariaLabel: Boolean(node.getAttribute("aria-label")), placeholder: Boolean(node.getAttribute("placeholder") || node.getAttribute("data-placeholder")), dataAttributes: attrs(node), className: String(node.className || "").slice(0, 120), rect: { x: Math.round(box.x), y: Math.round(box.y), width: Math.round(box.width), height: Math.round(box.height) }, fontSize: getComputedStyle(node).fontSize, fontWeight: getComputedStyle(node).fontWeight, ancestors: ancestors(node), titleClue: /title|subject|documenttitle|제목/i.test(meta), before, after }; });
    const titles = diagnostics.filter((item) => item.titleClue || (item.rect.y < 260 && item.rect.height < 180 && item.contenteditable === "true"));
    const bodies = diagnostics.filter((item) => item.contenteditable === "true" && !titles.includes(item) && item.rect.height >= 120);
    const editorRoot = Boolean(document.querySelector("[contenteditable='true']")) && Boolean(document.querySelector("[role='textbox'], [aria-label*='본문'], [class*='se-'], [class*='editor']"));
    const titleSelectors = [".se-component.se-documentTitle", ".se-documentTitle", ".se-title-text", ".se-documentTitle .se-title-text"];
    const titleSelectorCounts = Object.fromEntries(titleSelectors.map((selector) => [selector, document.querySelectorAll(selector).length]));
    const titleComponents = [...new Set(titleSelectors.slice(0, 2).flatMap((selector) => [...document.querySelectorAll(selector)]))].filter(visible);
    const titleTextRoots = [...new Set(titleComponents.flatMap((node) => (node.matches(".se-title-text") ? [node] : []).concat([...node.querySelectorAll(".se-title-text")])) )].filter(visible);
    const titleTargets = [...new Set(titleTextRoots.flatMap((root) => [...root.querySelectorAll("input, textarea, [contenteditable='true'], [role='textbox'], [aria-multiline='true'], p, span")]))].filter((node) => visible(node) && (node.matches("input, textarea, [contenteditable='true'], [role='textbox'], [aria-multiline='true'], p, span") || node.hasAttribute("tabindex"))).filter((node, _, all) => !all.some((other) => other !== node && node.contains(other)));
    const targetMeta = (node) => { const box = node.getBoundingClientRect(); return { tagName: node.tagName, className: String(node.className || "").split(/\s+/).filter((name) => /^se-/i.test(name)).slice(0, 4), role: node.getAttribute("role"), contenteditable: node.getAttribute("contenteditable"), tabindex: node.getAttribute("tabindex"), rect: { x: Math.round(box.x), y: Math.round(box.y), width: Math.round(box.width), height: Math.round(box.height) }, parentClass: String(node.parentElement?.className || "").split(/\s+/).filter((name) => /^se-/i.test(name)).slice(0, 4), childTags: [...node.children].slice(0, 8).map((child) => child.tagName), before: getComputedStyle(node, "::before").content, after: getComputedStyle(node, "::after").content }; };
    const titleComponentMeta = titleComponents.slice(0, 20).map(targetMeta);
    const titleTextRootMeta = titleTextRoots.slice(0, 20).map(targetMeta);
    const titleTargetMeta = titleTargets.slice(0, 20).map(targetMeta);
    const urlType = location.href.startsWith("about:blank") ? "ABOUT_BLANK" : /blog\.naver\.com/i.test(location.href) ? "NAVER_BLOG" : /naver\.com/i.test(location.href) ? "NAVER_OTHER" : "OTHER_ORIGIN";
    return { frameDetected: editorRoot || titles.length > 0 || bodies.length > 0, editorRootDetected: editorRoot, editorDetected: editorRoot && titleTargets.length === 1 && bodies.length === 1, titleDetected: titleTargets.length === 1, bodyDetected: bodies.length === 1, titleCandidateCount: titleTargets.length, bodyCandidateCount: bodies.length, titleComponentCount: titleComponents.length, titleTextRootCount: titleTextRoots.length, titleComponentMeta, titleTextRootMeta, titleTargetMeta, titleSelectorCounts, diagnostics, isTopFrame: window.top === window, originHostname: location.hostname, readyState: document.readyState, bodyPresent: Boolean(document.body), domCounts: { iframe: count("iframe"), input: count("input"), textarea: count("textarea"), contenteditable: count("[contenteditable]"), contenteditableTrue: count("[contenteditable='true']"), roleTextbox: count("[role='textbox']"), ariaMultiline: count("[aria-multiline]"), dataPlaceholder: count("[data-placeholder]") }, structureCandidates: { seClass: count("[class*='se-']"), editorClass: count("[class*='editor' i]"), documentClass: count("[class*='document' i]"), dataEditorLike: [...document.querySelectorAll("[data-]")].filter((node) => [...node.attributes].some((item) => /editor|document|title|body|placeholder/i.test(item.name))).length }, urlType };
  } }).then((results) => sendResponse({ frames: results.map((item) => ({ frameId: item.frameId, ...item.result })) })).catch(() => sendResponse({ frames: [], error: "EDITOR_FRAME_NOT_REACHABLE" }));
  return true;
});
