import { format } from "date-fns";
import { ko } from "date-fns/locale";
import { useEffect, useMemo, useState } from "react";
import { useAuth } from "../auth/AuthProvider";
import { buildGradeDashboardDiagnostics, type GradeDashboardDiagnostics } from "../domain/dashboardDiagnostics";
import { getOperationsPhase, type OperationsPhase } from "../domain/operationsState";
import { formatAuditAction, formatAuditSource, formatAuditTarget, safeLoadError } from "../domain/presentation";
import { isGradeAdminForGrade, isSystemOwner } from "../domain/scope";
import { summarizeStaffAssignmentsByGrade } from "../domain/staffAssignmentSummary";
import { listAuditLogs } from "../services/audit";
import { listClasses } from "../services/classes";
import { getOperationsSettings } from "../services/operations";
import { listPendingUsers } from "../services/pendingUsers";
import { listScopedPeriods } from "../services/scopedPeriods";
import { listScopedStudents } from "../services/scopedStudents";
import { getApplicableSelfStudyExceptions } from "../services/selfStudyExceptions";
import { listSelfStudyAttendanceHistory } from "../services/selfStudyReporting";
import { listSelfStudyGroupPeriods, listSelfStudyGroups, listSelfStudyMemberships, listSupervisionAssignments } from "../services/selfStudyOperations";
import { listAssignmentsForGrade, listAssignmentsForYear } from "../services/staffAssignments";
import { listUsers } from "../services/users";
import { useScope } from "../scope/ScopeProvider";
import type { OperationsSettings } from "../types/domain";

type Summary = GradeDashboardDiagnostics & { gradeId: string };
const zero: GradeDashboardDiagnostics = { studentCount: 0, classCount: 0, groupCount: 0, unassignedStudentCount: 0, missingGradeAdmin: false, missingHomeroomCount: 0, missingSupervisionCount: 0, presentCount: 0, excusedCount: 0, unexcusedCount: 0, missingAttendanceCount: 0 };
const phaseLabels: Record<OperationsPhase, string> = { normal: "\uC815\uC0C1 \uC6B4\uC601", read_only: "\uC77D\uAE30 \uC804\uC6A9", essential: "\uD544\uC218 \uC5C5\uBB34", notice: "\uC810\uAC80 \uC0AC\uC804\uACF5\uC9C0", maintenance: "\uC810\uAC80 \uC911", lockdown: "\uC811\uADFC \uC81C\uD55C" };
async function loadSummary(academicYearId: string, gradeId: string, date: string): Promise<Summary> { const scope = { academicYearId, gradeId }; const [students, classes, groups, memberships, edges, periods, assignments, supervision, exceptions, attendance] = await Promise.all([listScopedStudents(scope), listClasses(academicYearId, gradeId), listSelfStudyGroups(scope), listSelfStudyMemberships(scope), listSelfStudyGroupPeriods(scope), listScopedPeriods(academicYearId, gradeId), listAssignmentsForGrade(academicYearId, gradeId), listSupervisionAssignments(scope, { date }), getApplicableSelfStudyExceptions(scope, date), listSelfStudyAttendanceHistory({ ...scope, startDate: date, endDate: date })]); return { gradeId, ...buildGradeDashboardDiagnostics({ date, periods, students, classes, groups, memberships, edges, assignments, supervision, exceptions, attendance }) }; }
export function DashboardPage() {
 const { appUser }=useAuth(); const { scope, grades, assignments, years }=useScope(); const owner=isSystemOwner(appUser); const today=format(new Date(),"yyyy-MM-dd"); const admin=Boolean(scope?.gradeId&&appUser&&isGradeAdminForGrade(assignments,appUser.uid,scope.academicYearId,scope.gradeId)); const [summaries,setSummaries]=useState<Summary[]>([]); const [pending,setPending]=useState(0); const [staff,setStaff]=useState<any[]>([]); const [audits,setAudits]=useState<any[]>([]); const [operations,setOperations]=useState<OperationsSettings|null>(null); const [error,setError]=useState<string|null>(null);
 const scopes=useMemo(()=>!scope?[]:scope.gradeId?[{academicYearId:scope.academicYearId,gradeId:scope.gradeId}]:grades.filter(g=>g.active&&g.academicYearId===scope.academicYearId).map(g=>({academicYearId:scope.academicYearId,gradeId:g.id})),[scope,grades]);
 useEffect(()=>{ if(!scope||(!owner&&!admin)) return; let alive=true; void Promise.all(scopes.map(s=>loadSummary(s.academicYearId,s.gradeId,today))).then(v=>alive&&setSummaries(v)).catch(e=>alive&&setError(safeLoadError("dashboard",e,"\uB300\uC2DC\uBCF4\uB4DC\uB97C \uBD88\uB7EC\uC624\uC9C0 \uBABB\uD588\uC2B5\uB2C8\uB2E4."))); if(owner){void listPendingUsers().then(v=>alive&&setPending(v.length));void listAssignmentsForYear(scope.academicYearId).then(v=>alive&&setStaff(summarizeStaffAssignmentsByGrade(grades,v,scope.academicYearId)));void listAuditLogs(new Date(Date.now()-604800000),new Date()).then(v=>alive&&setAudits(v.slice(0,5)));void getOperationsSettings().then(v=>alive&&setOperations(v));} return()=>{alive=false;};},[scope,scopes,today,owner,admin,grades]);
 const total=summaries.reduce((r,v)=>({...r,studentCount:r.studentCount+v.studentCount,groupCount:r.groupCount+v.groupCount,missingSupervisionCount:r.missingSupervisionCount+v.missingSupervisionCount,missingAttendanceCount:r.missingAttendanceCount+v.missingAttendanceCount}),zero); const year=years.find(y=>y.id===scope?.academicYearId); const phase=getOperationsPhase(operations);
 if(!scope)return <section className="empty-state"><h2>{"\uD559\uB144\uB3C4 \uBC94\uC704\uB97C \uBD88\uB7EC\uC624\uB294 \uC911\uC785\uB2C8\uB2E4."}</h2></section>;
 return <><header className="page-header"><div><div className="eyebrow">{format(new Date(),"yyyy\uB144 M\uC6D4 d\uC77C EEEE",{locale:ko})}</div><h2>{owner?"\uD559\uAD50 \uC6B4\uC601 \uB300\uC2DC\uBCF4\uB4DC":"\uD559\uB144 \uC6B4\uC601 \uB300\uC2DC\uBCF4\uB4DC"}</h2><p className="muted">{year?.displayName??"-"}</p></div></header>{error&&<div className="empty-state text-danger">{error}</div>}<section className="card"><div className="dashboard-grid"><div><span>{"\uD559\uC0DD"}</span><strong>{total.studentCount}</strong></div><div><span>{"\uC790\uC2B5\uADF8\uB8F9"}</span><strong>{total.groupCount}</strong></div><div><span>{"\uAC10\uB3C5 \uBBF8\uBC30\uC815"}</span><strong>{total.missingSupervisionCount}</strong></div><div><span>{"\uCD9C\uACB0 \uBBF8\uC785\uB825"}</span><strong>{total.missingAttendanceCount}</strong></div></div></section>{owner&&<><section className="card"><h3>{"\uC2DC\uC2A4\uD15C \uC6B4\uC601 \uC0C1\uD0DC"}</h3><p><strong>{phaseLabels[phase]}</strong></p><p className="muted">{"\uBA85\uC2DC\uC801 \uC6B4\uC601 \uBAA8\uB4DC: "}{operations?.emergencyMode??"NORMAL"}</p><p>{"\uC2B9\uC778 \uB300\uAE30 \uACC4\uC815: "}{pending}</p></section><section className="card"><h3>{"\uD559\uB144\uBCC4 \uAD50\uC9C1\uC6D0 \uBC30\uC815 \uD604\uD669"}</h3>{staff.map(item=><p key={item.gradeId}>{item.gradeName}{": "}{item.assignedCount}{"\uBA85 / \uD559\uB144\uBD80 "}{item.gradeAdminCount}{"\uBA85"}</p>)}</section><section className="card"><h3>{"\uCD5C\uADFC \uAC10\uC0AC \uAE30\uB85D"}</h3>{audits.length? <ul>{audits.map(item=><li key={item.id}>{formatAuditAction(item.action)}{" · "}{formatAuditTarget(item.targetType)}{" · "}{formatAuditSource(item.source)}{" · "}{item.actorName??"-"}</li>)}</ul>:<p className="muted">{"\uCD5C\uADFC \uBCC0\uACBD \uAE30\uB85D\uC774 \uC5C6\uC2B5\uB2C8\uB2E4."}</p>}</section></>}</>;
}
