import { eachDayOfInterval, endOfMonth, endOfWeek, format, parseISO, startOfMonth, startOfWeek } from "date-fns";
import { ko } from "date-fns/locale";
import { useEffect, useMemo, useState } from "react";
import { useAuth } from "../auth/AuthProvider";
import { isGradeAdmin } from "../domain/access";
import { isSelfStudyDate } from "../domain/schedule";
import { dutyPeriodRowsToAssignments, parseDutyWorkbookByPeriod, type DutyPeriodImportRow } from "../lib/excel";
import { listDutyAssignmentsByRange, saveDutyAssignment, saveDutyAssignmentsBulk } from "../services/duty";
import { getSelfStudyException, listSelfStudyExceptions } from "../services/selfStudyExceptions";
import { listPeriods } from "../services/masterData";
import { listUsers } from "../services/users";
import type { AppUser, DutyAssignment, Period } from "../types/domain";

export function DutySchedulePage() {
  const { appUser } = useAuth(); const canEdit = isGradeAdmin(appUser); const [mode, setMode] = useState<"week" | "month">("month"); const [anchorDate, setAnchorDate] = useState(format(new Date(), "yyyy-MM-dd"));
  const [assignments, setAssignments] = useState<DutyAssignment[]>([]); const [periods, setPeriods] = useState<Period[]>([]); const [users, setUsers] = useState<AppUser[]>([]); const [importRows, setImportRows] = useState<DutyPeriodImportRow[]>([]); const [exceptionDates, setExceptionDates] = useState<Set<string>>(new Set()); const [busy, setBusy] = useState(false);
  const range = useMemo(() => { const base = parseISO(anchorDate); const start = mode === "month" ? startOfMonth(base) : startOfWeek(base, { weekStartsOn: 1 }); const end = mode === "month" ? endOfMonth(base) : endOfWeek(base, { weekStartsOn: 1 }); return { start: format(start, "yyyy-MM-dd"), end: format(end, "yyyy-MM-dd"), startDate: start, endDate: end }; }, [anchorDate, mode]);
  const days = useMemo(() => eachDayOfInterval({ start: range.startDate, end: range.endDate }), [range]); const activePeriods = periods.filter((period) => period.active);
  async function refresh() { const [duty, nextPeriods, exceptions] = await Promise.all([listDutyAssignmentsByRange(range.start, range.end), listPeriods(), listSelfStudyExceptions()]); setAssignments(duty); setPeriods(nextPeriods); setExceptionDates(new Set(exceptions.filter((item) => item.enabled).map((item) => item.date))); }
  useEffect(() => { void refresh(); }, [range.start, range.end]); useEffect(() => { if (canEdit) void listUsers().then((items) => setUsers(items.filter((item) => item.active))); }, [canEdit]);
  const assignmentMap = useMemo(() => new Map(assignments.map((item) => [item.date, item])), [assignments]);
  async function operational(date: string) { return isSelfStudyDate(date, await getSelfStudyException(date)); }
  async function changeManual(date: string, periodId: string, teacherUid: string) { if (!appUser || !canEdit || !teacherUid || !await operational(date)) return; const teacher = users.find((user) => user.uid === teacherUid); if (!teacher) return; const before = assignmentMap.get(date)?.periods[periodId] ?? null; await saveDutyAssignment({ date, periodId, teacherUid: teacher.uid, teacherName: teacher.displayName, teacherEmail: teacher.email }, { uid: appUser.uid, name: appUser.displayName }, before); await refresh(); }
  async function handleFile(file: File) { setBusy(true); try { const parsed = await parseDutyWorkbookByPeriod(file, users, activePeriods); setImportRows(await Promise.all(parsed.map(async (row) => row.error || isSelfStudyDate(row.date, await getSelfStudyException(row.date)) ? row : { ...row, error: "\uC790\uC728\uD559\uC2B5 \uC81C\uC678\uC77C\uC5D0\uB294 \uB2F4\uB2F9\uAD50\uC0AC\uB97C \uC9C0\uC815\uD560 \uC218 \uC5C6\uC2B5\uB2C8\uB2E4." }))); } finally { setBusy(false); } }
  async function applyImport() { if (!appUser || importRows.some((row) => row.error)) return; setBusy(true); try { await saveDutyAssignmentsBulk(dutyPeriodRowsToAssignments(importRows), { uid: appUser.uid, name: appUser.displayName }); setImportRows([]); await refresh(); } finally { setBusy(false); } }
  return <><header className="page-header"><div><div className="eyebrow">{"\uAD50\uC2DC\uBCC4 \uB2F4\uB2F9\uAD50\uC0AC \uC77C\uC815"}</div><h2>{"\uB2F4\uB2F9\uAD50\uC0AC \uC77C\uC815"}</h2></div></header><section className="toolbar card"><label>{"\uBCF4\uAE30"}<select value={mode} onChange={(event) => setMode(event.target.value as "week" | "month")}><option value="week">{"\uC8FC\uBCC4"}</option><option value="month">{"\uC6D4\uBCC4"}</option></select></label><label>{"\uAE30\uC900 \uB0A0\uC9DC"}<input type="date" value={anchorDate} onChange={(event) => setAnchorDate(event.target.value)} /></label></section>
  {canEdit && <section className="card import-card"><h3>{"Excel \uAD50\uC2DC\uBCC4 \uB2F4\uB2F9\uD45C"}</h3><input type="file" accept=".xlsx" onChange={(event) => event.target.files?.[0] && void handleFile(event.target.files[0])} />{importRows.length > 0 && <><p>{importRows.some((row) => row.error) ? "\uC624\uB958 \uD589\uC744 \uD655\uC778\uD558\uC138\uC694." : "\uC801\uC6A9\uD560 \uC218 \uC788\uC2B5\uB2C8\uB2E4."}</p><button disabled={busy || importRows.some((row) => row.error)} onClick={() => void applyImport()}>{"\uB2F4\uB2F9\uD45C \uC801\uC6A9"}</button></>}</section>}
  <section className="card"><div className="table-wrap"><table><thead><tr><th>{"\uB0A0\uC9DC"}</th><th>{"\uC694\uC77C"}</th>{activePeriods.map((period) => <th key={period.id}>{period.name}</th>)}</tr></thead><tbody>{days.map((day) => { const date = format(day, "yyyy-MM-dd"); const assignment = assignmentMap.get(date); const allowed = isSelfStudyDate(date); return <tr key={date}><td>{date}</td><td>{format(day, "EEE", { locale: ko })}</td>{activePeriods.map((period) => <td key={period.id}><select disabled={!canEdit || !allowed} value={assignment?.periods[period.id]?.teacherUid ?? ""} onChange={(event) => void changeManual(date, period.id, event.target.value)}><option value="">{"\uBBF8\uBC30\uC815"}</option>{users.map((user) => <option key={user.uid} value={user.uid}>{user.displayName}</option>)}</select>{!allowed && <span className="text-danger">{"\uC790\uC728\uD559\uC2B5 \uC81C\uC678\uC77C"}</span>}</td>)}</tr>; })}</tbody></table></div></section></>;
}
