import { endOfMonth, endOfWeek, format, parseISO, startOfMonth, startOfWeek, subDays } from "date-fns";
import { useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { useAuth } from "../auth/AuthProvider";
import { isGradeAdmin } from "../domain/access";
import { exportAttendanceExcel } from "../lib/excel";
import { listAttendanceByRange } from "../services/attendance";
import { listPeriods, listStudents } from "../services/masterData";
import { listUsers } from "../services/users";
import type { AttendanceRecord, AttendanceStatus, Period, Student } from "../types/domain";

const labels: Record<AttendanceStatus, string> = { present: "\uCD9C\uC11D", late: "\uC9C0\uAC01", absent: "\uACB0\uC11D", excused: "\uC778\uC815", early_leave: "\uC870\uD1F4" };
const text = { title: "\uC774\uC804 \uCD9C\uACB0", range: "\uAE30\uAC04", week: "\uC8FC\uBCC4", month: "\uC6D4\uBCC4", custom: "\uC9C1\uC811 \uC120\uD0DD", start: "\uC2DC\uC791\uC77C", end: "\uC885\uB8CC\uC77C", anchor: "\uAE30\uC900 \uB0A0\uC9DC", class: "\uBC18", student: "\uD559\uC0DD", period: "\uAD50\uC2DC", status: "\uC0C1\uD0DC", all: "\uC804\uCCB4", actor: "\uC785\uB825\uC790", search: "\uC870\uD68C", reset: "\uCD08\uAE30\uD654", excel: "Excel \uB2E4\uC6B4\uB85C\uB4DC", records: "\uAC1C \uAE30\uB85D", sort: "\uC815\uB82C", date: "\uB0A0\uC9DC", number: "\uBC88\uD638", note: "\uBE44\uACE0", updated: "\uC218\uC815 \uC2DC\uAC01", open: "\uC5F4\uAE30", rows: "\uD589 \uC218", previous: "\uC774\uC804", next: "\uB2E4\uC74C" };
type RangeMode = "week" | "month" | "custom";

export function HistoryPage() {
  const navigate = useNavigate(); const { appUser } = useAuth(); const canExport = isGradeAdmin(appUser);
  const [mode, setMode] = useState<RangeMode>("week"); const [anchor, setAnchor] = useState(format(new Date(), "yyyy-MM-dd")); const [start, setStart] = useState(format(subDays(new Date(), 7), "yyyy-MM-dd")); const [end, setEnd] = useState(format(new Date(), "yyyy-MM-dd"));
  const [records, setRecords] = useState<AttendanceRecord[]>([]); const [students, setStudents] = useState<Student[]>([]); const [periods, setPeriods] = useState<Period[]>([]);
  const [classId, setClassId] = useState(""); const [studentId, setStudentId] = useState(""); const [periodId, setPeriodId] = useState(""); const [status, setStatus] = useState<AttendanceStatus | "">(""); const [actorUid, setActorUid] = useState("");
  const [users, setUsers] = useState<{ uid: string; displayName: string }[]>([]); const [sort, setSort] = useState<"date" | "student">("date"); const [page, setPage] = useState(1); const [pageSize, setPageSize] = useState(25); const [busy, setBusy] = useState(false);
  const range = useMemo(() => { if (mode === "custom") return { start, end }; const date = parseISO(anchor); return mode === "week" ? { start: format(startOfWeek(date, { weekStartsOn: 1 }), "yyyy-MM-dd"), end: format(endOfWeek(date, { weekStartsOn: 1 }), "yyyy-MM-dd") } : { start: format(startOfMonth(date), "yyyy-MM-dd"), end: format(endOfMonth(date), "yyyy-MM-dd") }; }, [mode, anchor, start, end]);
  useEffect(() => { void Promise.all([listStudents(), listPeriods(), listUsers()]).then(([s, p, u]) => { setStudents(s); setPeriods(p); setUsers(u); }); }, []);
  async function search() { setBusy(true); try { setRecords(await listAttendanceByRange(range.start, range.end)); setPage(1); } finally { setBusy(false); } }
  useEffect(() => { void search(); }, [range.start, range.end]);
  const studentMap = useMemo(() => new Map(students.map((student) => [student.id, student])), [students]); const periodMap = useMemo(() => new Map(periods.map((period) => [period.id, period])), [periods]);
  const filtered = useMemo(() => records.filter((record) => (!classId || record.classId === classId) && (!studentId || record.studentId === studentId) && (!periodId || record.periodId === periodId) && (!status || record.status === status) && (!actorUid || record.markedBy === actorUid)).sort((a, b) => sort === "date" ? b.date.localeCompare(a.date) : (studentMap.get(a.studentId)?.name ?? "").localeCompare(studentMap.get(b.studentId)?.name ?? "", "ko")), [records, classId, studentId, periodId, status, actorUid, sort, studentMap]);
  const pageRows = filtered.slice((page - 1) * pageSize, page * pageSize); const pages = Math.max(1, Math.ceil(filtered.length / pageSize)); const reset = () => { setClassId(""); setStudentId(""); setPeriodId(""); setStatus(""); setActorUid(""); setSort("date"); setPage(1); }; const classes = [...new Set(students.map((student) => student.classId))].sort();
  return <><header className="page-header"><div><div className="eyebrow">{text.title}</div><h2>{text.title}</h2></div></header>
    <section className="card filter-grid"><label>{text.range}<select value={mode} onChange={(event) => setMode(event.target.value as RangeMode)}><option value="week">{text.week}</option><option value="month">{text.month}</option><option value="custom">{text.custom}</option></select></label>{mode === "custom" ? <><label>{text.start}<input type="date" value={start} onChange={(event) => setStart(event.target.value)} /></label><label>{text.end}<input type="date" value={end} onChange={(event) => setEnd(event.target.value)} /></label></> : <label>{text.anchor}<input type="date" value={anchor} onChange={(event) => setAnchor(event.target.value)} /></label>}<label>{text.class}<select value={classId} onChange={(event) => { setClassId(event.target.value); setStudentId(""); }}><option value="">{text.all}</option>{classes.map((value) => <option key={value}>{value}</option>)}</select></label><label>{text.student}<select value={studentId} onChange={(event) => setStudentId(event.target.value)}><option value="">{text.all}</option>{students.filter((student) => !classId || student.classId === classId).map((student) => <option key={student.id} value={student.id}>{student.name}</option>)}</select></label><label>{text.period}<select value={periodId} onChange={(event) => setPeriodId(event.target.value)}><option value="">{text.all}</option>{periods.map((period) => <option key={period.id} value={period.id}>{period.name}</option>)}</select></label><label>{text.status}<select value={status} onChange={(event) => setStatus(event.target.value as AttendanceStatus | "")}><option value="">{text.all}</option>{Object.entries(labels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>{text.actor}<select value={actorUid} onChange={(event) => setActorUid(event.target.value)}><option value="">{text.all}</option>{users.map((user) => <option key={user.uid} value={user.uid}>{user.displayName}</option>)}</select></label><div className="filter-actions"><button onClick={() => void search()} disabled={busy}>{text.search}</button><button onClick={reset}>{text.reset}</button>{canExport && <button onClick={() => void exportAttendanceExcel({ records: filtered, students, periods, filename: `attendance_${range.start}_${range.end}.xlsx` })}>{text.excel}</button>}</div></section>
    <section className="card"><div className="section-title-row"><h3>{filtered.length}{text.records}</h3><label>{text.sort}<select value={sort} onChange={(event) => setSort(event.target.value as "date" | "student")}><option value="date">{text.date}</option><option value="student">{text.student}</option></select></label></div><div className="table-wrap"><table><thead><tr><th>{text.date}</th><th>{text.class}</th><th>{text.number}</th><th>{text.student}</th><th>{text.period}</th><th>{text.status}</th><th>{text.note}</th><th>{text.actor}</th><th>{text.updated}</th><th /></tr></thead><tbody>{pageRows.map((record) => { const student = studentMap.get(record.studentId); return <tr key={record.id}><td>{record.date}</td><td>{record.classId}</td><td>{student?.studentNo}</td><td>{student?.name}</td><td>{periodMap.get(record.periodId)?.name}</td><td>{labels[record.status]}</td><td>{record.note}</td><td>{users.find((user) => user.uid === record.markedBy)?.displayName ?? record.markedBy}</td><td>{record.updatedAt && "toDate" in (record.updatedAt as object) ? (record.updatedAt as { toDate(): Date }).toDate().toLocaleString("ko-KR") : "-"}</td><td><button className="small" onClick={() => navigate(`/attendance?date=${record.date}`)}>{text.open}</button></td></tr>; })}</tbody></table></div><div className="action-row"><label>{text.rows}<select value={pageSize} onChange={(event) => { setPageSize(Number(event.target.value)); setPage(1); }}><option value={25}>25</option><option value={50}>50</option></select></label><button disabled={page === 1} onClick={() => setPage(page - 1)}>{text.previous}</button><span>{page} / {pages}</span><button disabled={page === pages} onClick={() => setPage(page + 1)}>{text.next}</button></div></section>
  </>;
}
