import { Timestamp } from "firebase/firestore";
import { useEffect, useState } from "react";
import { useAuth } from "../auth/AuthProvider";
import { DEFAULT_OPERATIONS_SETTINGS, getOperationsSettings, saveOperationsSettings } from "../services/operations";
import type { EmergencyMode, OperationsSettings } from "../types/domain";

const labels: Record<EmergencyMode, string> = { NORMAL: "정상 운영", READ_ONLY: "조회 전용", ESSENTIAL_ONLY: "필수 자습 운영", MAINTENANCE: "시스템 점검", LOCKDOWN: "일반 사용자 접근 제한" };
const toInput = (value: unknown) => value && typeof value === "object" && "toDate" in value ? (value as { toDate(): Date }).toDate().toISOString().slice(0, 16) : "";
const toTimestamp = (value: string) => value ? Timestamp.fromDate(new Date(value)) : null;

export function OperationsPage() {
  const { appUser } = useAuth(); const [value, setValue] = useState<OperationsSettings>(DEFAULT_OPERATIONS_SETTINGS); const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string | null>(null);
  useEffect(() => { void getOperationsSettings().then(setValue).catch(() => setMessage("운영 설정을 불러오지 못했습니다.")); }, []);
  async function save() { if (!appUser) return; const warning = value.emergencyMode === "LOCKDOWN" ? "LOCKDOWN으로 전환하면 일반 사용자의 접근이 제한됩니다. 계속하시겠습니까?" : value.emergencyMode === "READ_ONLY" ? "시스템을 조회 전용 상태로 전환하시겠습니까?" : "운영 설정을 저장하시겠습니까?"; if (!confirm(warning)) return; setBusy(true); setMessage(null); try { await saveOperationsSettings(value, appUser.uid); setMessage("운영 설정을 저장했습니다."); } catch (error) { setMessage(error instanceof Error ? error.message : "운영 설정 저장에 실패했습니다."); } finally { setBusy(false); } }
  const maintenance = value.maintenance;
  return <><header className="page-header"><div><div className="eyebrow">학교 운영</div><h2>시스템 운영 및 점검</h2></div></header>{message && <div className="empty-state">{message}</div>}<section className="card"><label>운영 모드<select value={value.emergencyMode} onChange={(event) => setValue({ ...value, emergencyMode: event.target.value as EmergencyMode })}>{Object.entries(labels).map(([mode,label]) => <option key={mode} value={mode}>{mode} · {label}</option>)}</select></label><p className="muted">{labels[value.emergencyMode]}</p><label>안내 메시지<textarea value={value.emergencyMessage} onChange={(event) => setValue({ ...value, emergencyMessage: event.target.value })} /></label></section><section className="card"><h3>예약 점검</h3><label><input type="checkbox" checked={maintenance.enabled} onChange={(event) => setValue({ ...value, maintenance: { ...maintenance, enabled: event.target.checked } })} /> 점검 예약 사용</label><div className="filter-grid"><label>제목<input value={maintenance.title} onChange={(event) => setValue({ ...value, maintenance: { ...maintenance, title: event.target.value } })}/></label><label>안내 시작<input type="datetime-local" value={toInput(maintenance.noticeFrom)} onChange={(event) => setValue({ ...value, maintenance: { ...maintenance, noticeFrom: toTimestamp(event.target.value) } })}/></label><label>점검 시작<input type="datetime-local" value={toInput(maintenance.startsAt)} onChange={(event) => setValue({ ...value, maintenance: { ...maintenance, startsAt: toTimestamp(event.target.value) } })}/></label><label>점검 종료<input type="datetime-local" value={toInput(maintenance.endsAt)} onChange={(event) => setValue({ ...value, maintenance: { ...maintenance, endsAt: toTimestamp(event.target.value) } })}/></label></div><label>안내 내용<textarea value={maintenance.message} onChange={(event) => setValue({ ...value, maintenance: { ...maintenance, message: event.target.value } })}/></label><label><input type="checkbox" checked={maintenance.bannerEnabled} onChange={(event) => setValue({ ...value, maintenance: { ...maintenance, bannerEnabled: event.target.checked } })}/> 배너 표시</label><label><input type="checkbox" checked={maintenance.popupEnabled} onChange={(event) => setValue({ ...value, maintenance: { ...maintenance, popupEnabled: event.target.checked } })}/> 팝업 표시</label></section><div className="action-row"><button disabled={busy} onClick={() => void save()}>{busy ? "저장 중..." : "저장"}</button></div></>;
}
