import { useEffect, useMemo, useState } from "react";
import { format, startOfMonth } from "date-fns";
import { useAuth } from "../auth/AuthProvider";
import { isGradeAdminForGrade, isSystemOwner } from "../domain/scope";
import { SELF_STUDY_ATTENDANCE_LABELS } from "../domain/selfStudyOperation";
import { exportStatsExcel } from "../lib/excel";
import { listClasses } from "../services/classes";
import { listScopedPeriods } from "../services/scopedPeriods";
import { listScopedStudents } from "../services/scopedStudents";
import { listSelfStudyGroups } from "../services/selfStudyOperations";
import { listSelfStudyAttendanceHistory } from "../services/selfStudyReporting";
import { useScope } from "../scope/ScopeProvider";
import type { SelfStudyAttendanceRecord, SelfStudyAttendanceStatus } from "../types/domain";

export function SelfStudyHistoryPage() {
  const { appUser } = useAuth(); const { scope, assignments } = useScope();
  const [start, setStart] = useState(format(startOfMonth(new Date()), "yyyy-MM-dd")); const [end, setEnd] = useState(format(new Date(), "yyyy-MM-dd")); const [classId, setClassId] = useState(""); const [groupId, setGroupId] = useState(""); const [periodId, setPeriodId] = useState(""); const [studentId, setStudentId] = useState(""); const [status, setStatus] = useState<SelfStudyAttendanceStatus | "">("");
  const [records, setRecords] = useState<SelfStudyAttendanceRecord[]>([]); const [classes, setClasses] = useState<any[]>([]); const [students, setStudents] = useState<any[]>([]); const [periods, setPeriods] = useState<any[]>([]); const [groups, setGroups] = useState<any[]>([]); const [error, setError] = useState<string | null>(null);
  const current = scope?.gradeId ? { academicYearId: scope.academicYearId, gradeId: scope.gradeId } : null; const owner = isSystemOwner(appUser); const admin = Boolean(appUser && current && isGradeAdminForGrade(assignments, appUser.uid, current.academicYearId, current.gradeId));
  useEffect(() => { if (!current) return; void Promise.all([listClasses(current.academicYearId,current.gradeId), listScopedStudents(current), listScopedPeriods(current.academicYearId,current.gradeId), listSelfStudyGroups(current)]).then(([c,s,p,g]) => { setClasses(c); setStudents(s); setPeriods(p); setGroups(g); const own = c.find((item) => item.active && item.homeroomTeacherUid === appUser?.uid); if (!owner && !admin) setClassId(own?.id ?? ""); }); }, [current?.academicYearId,current?.gradeId,appUser?.uid,owner,admin]);
  async function load() { if (!current || (!owner && !admin && !classId)) return; try { setError(null); setRecords(await listSelfStudyAttendanceHistory({ ...current,startDate:start,endDate:end,...(classId?{classId}:{}),...(groupId?{selfStudyGroupId:groupId}:{}),...(periodId?{periodId}:{}),...(studentId?{studentId}:{}),...(status?{status}:{}) })); } catch (e) { setError(e instanceof Error ? e.message : "자습 출결 이력을 불러오지 못했습니다."); } }
  useEffect(() => { void load(); }, [current?.academicYearId,current?.gradeId,start,end,classId,groupId,periodId,studentId,status]);
  const studentMap = useMemo(() => new Map(students.map((x) => [x.id,x])),[students]); const periodMap = useMemo(() => new Map(periods.map((x) => [x.id,x])),[periods]); const groupMap = useMemo(() => new Map(groups.map((x) => [x.id,x])),[groups]);
  if (!current) return <section className="empty-state"><h2>학년을 선택하세요.</h2></section>;
  if (!owner && !admin && !classId) return <section className="empty-state"><h2>담임 반 출결 이력만 조회할 수 있습니다.</h2></section>;
  return <><header className="page-header"><div><div className="eyebrow">자습 출결 이력</div><h2>자습 출결 이력</h2></div><button onClick={() => void exportStatsExcel(records.map((r)=>({날짜:r.date,교시:periodMap.get(r.periodId)?.name??r.periodId,반:r.classId,학생:studentMap.get(r.studentId)?.name??r.studentId,자습그룹:groupMap.get(r.selfStudyGroupId)?.displayName??r.selfStudyGroupId,상태:SELF_STUDY_ATTENDANCE_LABELS[r.status],승인사유:r.permissionReasonText??"",입력자:r.recordedByUid})),`self_study_history_${start}_${end}.xlsx`)}>Excel 다운로드</button></header>{error&&<div className="empty-state text-danger">{error}</div>}<section className="card filter-grid"><label>시작<input type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label>종료<input type="date" value={end} onChange={e=>setEnd(e.target.value)}/></label><label>반<select value={classId} disabled={!owner&&!admin} onChange={e=>setClassId(e.target.value)}><option value="">전체</option>{classes.filter((c)=>c.active).map(c=><option key={c.id} value={c.id}>{c.displayName}</option>)}</select></label><label>그룹<select value={groupId} onChange={e=>setGroupId(e.target.value)}><option value="">전체</option>{groups.filter(g=>g.active).map(g=><option key={g.id} value={g.id}>{g.displayName}</option>)}</select></label><label>교시<select value={periodId} onChange={e=>setPeriodId(e.target.value)}><option value="">전체</option>{periods.filter(p=>p.active).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>상태<select value={status} onChange={e=>setStatus(e.target.value as SelfStudyAttendanceStatus|"")}><option value="">전체</option>{Object.entries(SELF_STUDY_ATTENDANCE_LABELS).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label></section><section className="card table-wrap"><table><thead><tr><th>날짜</th><th>교시</th><th>학생</th><th>반</th><th>그룹</th><th>상태</th><th>승인 사유</th><th>입력자</th></tr></thead><tbody>{records.map(r=><tr key={r.id}><td>{r.date}</td><td>{periodMap.get(r.periodId)?.name??r.periodId}</td><td>{studentMap.get(r.studentId)?.name??r.studentId}</td><td>{r.classId}</td><td>{groupMap.get(r.selfStudyGroupId)?.displayName??r.selfStudyGroupId}</td><td>{SELF_STUDY_ATTENDANCE_LABELS[r.status]}</td><td>{r.permissionReasonText??"-"}</td><td>{r.recordedByUid}</td></tr>)}</tbody></table></section></>;
}
