import { useEffect, useState } from "react";
import { useAuth } from "../auth/AuthProvider";
import { isGradeAdminForGrade, isSystemOwner } from "../domain/scope";
import { safeLoadError } from "../domain/presentation";
import { listScopedPeriods } from "../services/scopedPeriods";
import { deactivateSelfStudyException, listSelfStudyExceptions, saveSelfStudyException } from "../services/selfStudyExceptions";
import { useScope } from "../scope/ScopeProvider";
import type { SelfStudyException, SelfStudyExceptionReasonType } from "../types/domain";

const today = () => new Date(Date.now() - new Date().getTimezoneOffset() * 60_000).toISOString().slice(0, 10);

export function SelfStudyExceptionsPage() {
  const { appUser } = useAuth(); const { scope, assignments } = useScope();
  const [items, setItems] = useState<SelfStudyException[]>([]); const [periods, setPeriods] = useState<any[]>([]); const [periodIds, setPeriodIds] = useState<string[]>([]);
  const [date, setDate] = useState(today()); const [scopeType, setScopeType] = useState<"school" | "grade">("grade"); const [reasonType, setReasonType] = useState<SelfStudyExceptionReasonType>("manual"); const [reason, setReason] = useState(""); const [error, setError] = useState<string | null>(null);
  const current = scope?.gradeId ? { academicYearId: scope.academicYearId, gradeId: scope.gradeId } : null; const owner = isSystemOwner(appUser); const admin = Boolean(appUser && current && isGradeAdminForGrade(assignments, appUser.uid, current.academicYearId, current.gradeId)); const actor = appUser ? { uid: appUser.uid, name: appUser.displayName } : null;
  async function refresh() { if (!current) return; const [nextItems, nextPeriods] = await Promise.all([listSelfStudyExceptions(current), listScopedPeriods(current.academicYearId, current.gradeId)]); setItems(nextItems); setPeriods(nextPeriods); }
  useEffect(() => { void refresh().catch((caught) => setError(safeLoadError("selfStudyExceptions", caught))); }, [current?.academicYearId, current?.gradeId]);
  async function save() { if (!current || !actor) return; try { if (!owner && scopeType === "school") throw new Error("학교 전체 제외일은 최고관리자만 관리할 수 있습니다."); await saveSelfStudyException({ academicYearId: current.academicYearId, gradeId: scopeType === "grade" ? current.gradeId : null, scopeType, date, reasonType, reason, active: true, ...(periodIds.length ? { periodIds } : {}) }, actor); setReason(""); setPeriodIds([]); await refresh(); } catch (caught) { setError(caught instanceof Error ? caught.message : "저장에 실패했습니다."); } }
  if (!current) return <section className="empty-state"><h2>학년을 선택하세요.</h2></section>;
  if (!owner && !admin) return <section className="empty-state"><h2>제외일 관리 권한이 없습니다.</h2></section>;
  return <><header className="page-header"><div><div className="eyebrow">자습 운영 제외일</div><h2>자습 운영 제외일</h2></div></header>{error && <div className="empty-state text-danger">{error}</div>}<section className="card filter-grid"><label>날짜<input type="date" value={date} onChange={(e) => setDate(e.target.value)} /></label><label>범위<select value={scopeType} disabled={!owner} onChange={(e) => setScopeType(e.target.value as "school" | "grade")}><option value="grade">현재 학년</option>{owner && <option value="school">학교 전체</option>}</select></label><label>유형<select value={reasonType} onChange={(e) => setReasonType(e.target.value as SelfStudyExceptionReasonType)}><option value="holiday">공휴일</option><option value="exam">시험</option><option value="school_event">학교행사</option><option value="manual">수동</option></select></label><label>사유<input value={reason} onChange={(e) => setReason(e.target.value)} /></label><button onClick={() => void save()}>저장</button></section><section className="card"><h3>제외 교시</h3><p className="muted">선택하지 않으면 종일 제외입니다. 선택한 교시만 제외할 수도 있습니다.</p>{periods.filter((period) => period.active).map((period) => <label key={period.id}><input type="checkbox" checked={periodIds.includes(period.id)} onChange={() => setPeriodIds((ids) => ids.includes(period.id) ? ids.filter((id) => id !== period.id) : [...ids, period.id])} /> {period.name}</label>)}</section><section className="card table-wrap"><table><thead><tr><th>날짜</th><th>범위</th><th>교시</th><th>사유</th><th>상태</th><th /></tr></thead><tbody>{items.map((item) => <tr key={`${item.scopeType}_${item.gradeId}_${item.date}`}><td>{item.date}</td><td>{item.scopeType === "school" ? "학교 전체" : item.gradeId}</td><td>{item.periodIds?.map((id) => periods.find((period) => period.id === id)?.name ?? id).join(", ") || "종일"}</td><td>{item.reason}</td><td>{item.active === false ? "비활성" : "활성"}</td><td>{item.active !== false && <button className="small" onClick={() => actor && void deactivateSelfStudyException(item, actor).then(refresh)}>비활성화</button>}</td></tr>)}</tbody></table></section></>;
}
