import { FormEvent, useEffect, useMemo, useState } from "react";
import { useAuth } from "../auth/AuthProvider";
import { createSelfStudyGroup, listSelfStudyGroupPeriods, listSelfStudyGroups, listSelfStudyMemberships, saveSelfStudyGroup, saveSelfStudyGroupPeriod, saveSelfStudyMembership } from "../services/selfStudyOperations";
import { listScopedPeriods } from "../services/scopedPeriods";
import { listScopedStudents } from "../services/scopedStudents";
import { listClasses } from "../services/classes";
import { useScope } from "../scope/ScopeProvider";
import type { SelfStudyGroup } from "../types/domain";

const label = (type: "REGULAR" | "READING") => type === "READING" ? "독서실" : "일반 자습실";

export function SelfStudyGroupsPage() {
  const { appUser } = useAuth(); const { scope, loading: scopeLoading } = useScope();
  const [groups, setGroups] = useState<SelfStudyGroup[]>([]); const [edges, setEdges] = useState<any[]>([]); const [memberships, setMemberships] = useState<any[]>([]); const [periods, setPeriods] = useState<any[]>([]); const [students, setStudents] = useState<any[]>([]); const [classes, setClasses] = useState<any[]>([]);
  const [name, setName] = useState(""); const [type, setType] = useState<"REGULAR" | "READING">("REGULAR"); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  const scoped = Boolean(scope?.gradeId); const actor = appUser ? { uid: appUser.uid, name: appUser.displayName } : null;
  async function refresh() { if (!scope?.gradeId) return; setBusy(true); setError(null); try { const s = { academicYearId: scope.academicYearId, gradeId: scope.gradeId }; const [g,e,m,p,st,c] = await Promise.all([listSelfStudyGroups(s), listSelfStudyGroupPeriods(s), listSelfStudyMemberships(s), listScopedPeriods(s.academicYearId,s.gradeId), listScopedStudents(s), listClasses(s.academicYearId,s.gradeId)]); setGroups(g); setEdges(e); setMemberships(m); setPeriods(p); setStudents(st); setClasses(c); } catch (x) { setError(x instanceof Error ? x.message : "자습 운영 정보를 불러오지 못했습니다."); } finally { setBusy(false); } }
  useEffect(() => { void refresh(); }, [scope?.academicYearId, scope?.gradeId]);
  const groupById = useMemo(() => new Map(groups.map((g) => [g.id,g])), [groups]); const classById = useMemo(() => new Map(classes.map((c) => [c.id,c])), [classes]); const memberByStudent = useMemo(() => new Map(memberships.filter((m) => m.active).map((m) => [m.studentId,m])), [memberships]);
  async function create(e: FormEvent) { e.preventDefault(); if (!scope?.gradeId || !actor) return; try { await createSelfStudyGroup({ academicYearId:scope.academicYearId, gradeId:scope.gradeId, displayName:name, type, active:true, sortOrder:groups.length + 1 }, actor); setName(""); await refresh(); } catch(x) { setError(x instanceof Error ? x.message : "그룹을 만들지 못했습니다."); } }
  async function changeGroup(group: SelfStudyGroup, values: Partial<SelfStudyGroup>) { if (!actor) return; if (values.active === false && !confirm("비활성화해도 기존 운영교시와 학생 배정 기록은 삭제되지 않습니다.")) return; try { await saveSelfStudyGroup({...group,...values},actor,group); await refresh(); } catch(x) { setError(x instanceof Error ? x.message : "그룹을 저장하지 못했습니다."); } }
  async function togglePeriod(group: SelfStudyGroup, period: any, active: boolean) { if (!actor || !group.active || !period.active) return; const before = edges.find((e) => e.groupId===group.id && e.periodId===period.id); try { await saveSelfStudyGroupPeriod({academicYearId:group.academicYearId,gradeId:group.gradeId,groupId:group.id,periodId:period.id,active},actor,before); await refresh(); } catch(x) { setError(x instanceof Error ? x.message : "운영 교시를 저장하지 못했습니다."); } }
  async function assign(student:any, groupId:string) { if (!actor || !scope?.gradeId) return; const before=memberByStudent.get(student.id); const group=groupById.get(groupId); if (!groupId && before) { try { await saveSelfStudyMembership({...before, active:false},actor,before); await refresh(); } catch(x) { setError(x instanceof Error ? x.message : "학생 자습실을 저장하지 못했습니다."); } return; } if (!group) return; try { await saveSelfStudyMembership({academicYearId:scope.academicYearId,gradeId:scope.gradeId,studentId:student.id,classId:student.classId,selfStudyGroupId:groupId,active:true},actor,before); await refresh(); } catch(x) { setError(x instanceof Error ? x.message : "학생 자습실을 저장하지 못했습니다."); } }
  if(scopeLoading) return <div className="empty-state">불러오는 중...</div>; if(!scoped) return <section className="empty-state"><h2>학년을 선택하세요.</h2><p>전체 학년 범위에서는 자습 운영을 관리할 수 없습니다.</p></section>;
  return <><header className="page-header"><div><div className="eyebrow">SELF STUDY OPERATIONS</div><h2>자습 운영 관리</h2></div></header>{error&&<div className="empty-state text-danger">{error}</div>}<div className="grid two"><form className="card" onSubmit={(e)=>void create(e)}><h3>자습실/독서실 추가</h3><label>이름<input value={name} onChange={e=>setName(e.target.value)} required /></label><label>유형<select value={type} onChange={e=>setType(e.target.value as any)}><option value="REGULAR">일반 자습실</option><option value="READING">독서실</option></select></label><button className="primary" disabled={busy}>추가</button></form><section className="card"><h3>운영 기준</h3><p>자습실별 운영 교시와 학생 배정은 별도입니다.</p><p className="muted">학생의 반 소속은 변경하지 않습니다.</p></section></div><section className="card"><h3>자습실 운영</h3>{groups.length===0?<div className="empty-state">등록된 자습실/독서실이 없습니다.</div>:<div className="table-wrap"><table><thead><tr><th>이름</th><th>유형</th><th>운영 교시</th><th>배정 학생</th><th>상태</th><th>관리</th></tr></thead><tbody>{groups.map(g=><tr key={g.id}><td><input defaultValue={g.displayName} onBlur={e=>e.target.value!==g.displayName&&void changeGroup(g,{displayName:e.target.value})}/></td><td>{label(g.type)}</td><td>{periods.map(p=><label key={p.id}><input type="checkbox" checked={Boolean(edges.find(e=>e.groupId===g.id&&e.periodId===p.id)?.active)} disabled={!g.active||!p.active} onChange={e=>void togglePeriod(g,p,e.target.checked)}/>{p.name}</label>)}</td><td>{memberships.filter(m=>m.active&&m.selfStudyGroupId===g.id).length}명</td><td>{g.active?"활성":"비활성"}</td><td><button onClick={()=>void changeGroup(g,{active:!g.active})}>{g.active?"비활성화":"활성화"}</button></td></tr>)}</tbody></table></div>}</section><section className="card"><h3>학생 자습실 배정</h3>{students.length===0?<div className="empty-state">현재 학년 학생이 없습니다.</div>:<div className="table-wrap"><table><thead><tr><th>반</th><th>학번</th><th>학생</th><th>자습실</th><th>상태</th></tr></thead><tbody>{students.map(s=>{const m=memberByStudent.get(s.id);return <tr key={s.id}><td>{classById.get(s.classId)?.displayName??s.classId}</td><td>{s.studentNo}</td><td>{s.name}</td><td><select value={m?.selfStudyGroupId??""} onChange={e=>void assign(s,e.target.value)}><option value="">미배정</option>{groups.filter(g=>g.active).map(g=><option value={g.id} key={g.id}>{g.displayName} ({label(g.type)})</option>)}</select></td><td>{m?label(groupById.get(m.selfStudyGroupId)?.type??"REGULAR"):"미배정"}</td></tr>})}</tbody></table></div>}</section></>;
}
