import { useEffect, useMemo, useState } from "react";
import { useAuth } from "../auth/AuthProvider";
import { isSystemOwner } from "../domain/scope";
import { SELF_STUDY_PERMISSION_REASON_CODES } from "../domain/selfStudyOperation";
import { listClasses } from "../services/classes";
import { listScopedPeriods } from "../services/scopedPeriods";
import { listScopedStudents } from "../services/scopedStudents";
import { cancelSelfStudyPermission, listSelfStudyGroupPeriods, listSelfStudyGroups, listSelfStudyMemberships, listSelfStudyPermissions, saveSelfStudyPermission } from "../services/selfStudyOperations";
import { useScope } from "../scope/ScopeProvider";
import type { SelfStudyPermission, SelfStudyPermissionReasonCode } from "../types/domain";

const reasonLabels: Record<SelfStudyPermissionReasonCode, string> = { ACADEMY: "학원", MEDICAL: "병원/의료", FAMILY: "가정사", SCHOOL_ACTIVITY: "학교활동", OTHER: "기타" };
const today = () => new Date(Date.now() - new Date().getTimezoneOffset() * 60_000).toISOString().slice(0, 10);

export function SelfStudyPermissionsPage() {
  const { appUser } = useAuth(); const { scope, loading: scopeLoading } = useScope();
  const [date, setDate] = useState(today()); const [classId, setClassId] = useState(""); const [selectedStudentId, setSelectedStudentId] = useState("");
  const [classes, setClasses] = useState<any[]>([]); const [students, setStudents] = useState<any[]>([]); const [periods, setPeriods] = useState<any[]>([]); const [memberships, setMemberships] = useState<any[]>([]); const [groups, setGroups] = useState<any[]>([]); const [edges, setEdges] = useState<any[]>([]); const [permissions, setPermissions] = useState<SelfStudyPermission[]>([]);
  const [periodIds, setPeriodIds] = useState<string[]>([]); const [reasonCode, setReasonCode] = useState<SelfStudyPermissionReasonCode>("ACADEMY"); const [reasonText, setReasonText] = useState(""); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  const owner = isSystemOwner(appUser); const actor = appUser ? { uid: appUser.uid, name: appUser.displayName } : null;
  async function refresh() {
    if (!scope?.gradeId || !appUser) return; setBusy(true); setError(null);
    try { const current = { academicYearId: scope.academicYearId, gradeId: scope.gradeId }; const [nextClasses,nextStudents,nextPeriods,nextMemberships,nextGroups,nextEdges] = await Promise.all([listClasses(current.academicYearId,current.gradeId),listScopedStudents(current),listScopedPeriods(current.academicYearId,current.gradeId),listSelfStudyMemberships(current),listSelfStudyGroups(current),listSelfStudyGroupPeriods(current)]); const own = nextClasses.find((item) => item.active && item.homeroomTeacherUid === appUser.uid); const nextClassId = owner ? (classId && nextClasses.some((item) => item.id === classId) ? classId : nextClasses.find((item) => item.active)?.id ?? "") : own?.id ?? ""; setClasses(nextClasses);setStudents(nextStudents);setPeriods(nextPeriods);setMemberships(nextMemberships);setGroups(nextGroups);setEdges(nextEdges);setClassId(nextClassId); if (nextClassId) setPermissions(await listSelfStudyPermissions(current,date,nextClassId)); else setPermissions([]); }
    catch (caught) { setError(caught instanceof Error ? caught.message : "자습 예외 정보를 불러오지 못했습니다."); } finally { setBusy(false); }
  }
  useEffect(() => { void refresh(); }, [scope?.academicYearId,scope?.gradeId,date,appUser?.uid,classId]);
  const selectedStudent = students.find((item) => item.id === selectedStudentId && item.classId === classId);
  const membership = selectedStudent ? memberships.find((item) => item.active && item.studentId === selectedStudent.id) : null;
  const group = membership ? groups.find((item) => item.id === membership.selfStudyGroupId && item.active) : null;
  const availablePeriods = useMemo(() => periods.filter((period) => period.active && group && edges.some((edge) => edge.active && edge.groupId === group.id && edge.periodId === period.id)), [periods, group, edges]);
  const existing = selectedStudent ? permissions.find((item) => item.studentId === selectedStudent.id && item.active) : null;
  useEffect(() => { if (!existing) { setPeriodIds([]); setReasonCode("ACADEMY"); setReasonText(""); return; } setPeriodIds(existing.periodIds); setReasonCode(existing.reasonCode); setReasonText(existing.reasonText); }, [existing?.id, selectedStudentId]);
  async function save() { if (!scope?.gradeId || !actor || !selectedStudent || !membership || !group) return; try { await saveSelfStudyPermission({academicYearId:scope.academicYearId,gradeId:scope.gradeId,classId,studentId:selectedStudent.id,date,periodIds,reasonCode,reasonText,active:true,approvedByUid:actor.uid},actor,existing ?? null,{isSystemOwner:owner}); setSelectedStudentId(""); await refresh(); } catch(caught) { setError(caught instanceof Error ? caught.message : "자습 예외를 저장하지 못했습니다."); } }
  async function cancel() { if (!actor || !existing || !confirm("이 자습 예외를 취소할까요?")) return; try { await cancelSelfStudyPermission(existing,actor,{isSystemOwner:owner}); setSelectedStudentId(""); await refresh(); } catch(caught) { setError(caught instanceof Error ? caught.message : "자습 예외를 취소하지 못했습니다."); } }
  if (scopeLoading) return <div className="empty-state">불러오는 중...</div>;
  if (!scope?.gradeId) return <section className="empty-state"><h2>학년을 선택하세요.</h2><p>자습 예외는 특정 학년 범위에서만 관리할 수 있습니다.</p></section>;
  if (!owner && !classes.some((item) => item.active && item.homeroomTeacherUid === appUser?.uid)) return <section className="empty-state"><h2>담임 반이 없습니다.</h2><p>자습 예외 변경은 자기 담임 반의 학생에게만 가능합니다.</p></section>;
  return <><header className="page-header"><div><div className="eyebrow">자습 예외 관리</div><h2>학생 자습 예외</h2></div><label>날짜<input type="date" value={date} onChange={(event) => setDate(event.target.value)} /></label></header>{error&&<div className="empty-state text-danger">{error}</div>}<section className="card"><label>반<select value={classId} disabled={!owner} onChange={(event)=>{setClassId(event.target.value);setSelectedStudentId("");}}>{classes.filter((item)=>item.active&&(owner||item.homeroomTeacherUid===appUser?.uid)).map((item)=><option key={item.id} value={item.id}>{item.displayName}</option>)}</select></label><div className="table-wrap"><table><thead><tr><th>학번</th><th>학생</th><th>자습 그룹</th><th>현재 예외</th><th>관리</th></tr></thead><tbody>{students.filter((item)=>item.active&&item.classId===classId).map((student)=>{const member=memberships.find((item)=>item.active&&item.studentId===student.id);const activeGroup=member&&groups.find((item)=>item.id===member.selfStudyGroupId&&item.active);const permission=permissions.find((item)=>item.active&&item.studentId===student.id);return <tr key={student.id}><td>{student.studentNo}</td><td>{student.name}</td><td>{activeGroup?.displayName??"자습 그룹 미배정"}</td><td>{permission?`${reasonLabels[permission.reasonCode]} · ${permission.periodIds.length}개 교시`:"없음"}</td><td><button type="button" disabled={!activeGroup} onClick={()=>setSelectedStudentId(student.id)}>{permission?"수정":"예외 등록"}</button></td></tr>})}</tbody></table></div></section>{selectedStudent&&<section className="card"><h3>{selectedStudent.name} / {classes.find((item)=>item.id===classId)?.displayName}</h3>{!group?<p className="text-danger">현재 자습 그룹에 배정되지 않은 학생입니다.</p>:<><div>{availablePeriods.map((period)=><label key={period.id}><input type="checkbox" checked={periodIds.includes(period.id)} onChange={(event)=>setPeriodIds(event.target.checked?[...periodIds,period.id]:periodIds.filter((id)=>id!==period.id))}/>{period.name}</label>)}</div><label>사유<select value={reasonCode} onChange={(event)=>setReasonCode(event.target.value as SelfStudyPermissionReasonCode)}>{SELF_STUDY_PERMISSION_REASON_CODES.map((code)=><option key={code} value={code}>{reasonLabels[code]}</option>)}</select></label><label>사유 상세<input value={reasonText} onChange={(event)=>setReasonText(event.target.value)} /></label><button className="primary" disabled={busy||periodIds.length===0||!reasonText.trim()} onClick={()=>void save()}>저장</button>{existing&&<button type="button" onClick={()=>void cancel()}>취소</button>}<button type="button" onClick={()=>setSelectedStudentId("")}>닫기</button></>}</section>}</>;
}
